### ISSUE TITLE
./start errors out with complaints about not found wintricks directories 

### ISSUE THREAD

**Issue by woeisme** [mmmaxwwwell/space-engineers-dedicated-docker-linux#4] opened 2021-02-09 23:25 UTC
> space-engineers-dedicated-docker-linux | cp: cannot create regular file '/home/wine/.steam/steamcmd/': Not a directory
space-engineers-dedicated-docker-linux | cp: cannot create regular file '/home/wine/.steam/steamcmd/linux32/': No such file or directory
space-engineers-dedicated-docker-linux | /usr/games/steamcmd: 24: exec: /home/wine/.steam/steamcmd/steamcmd.sh: not found
space-engineers-dedicated-docker-linux | /entrypoint-space_engineers.bash: line 3: /home/wine/.bash_profile: No such file or directory
space-engineers-dedicated-docker-linux | /entrypoint-space_engineers.bash: line 4: cd: /appdata/space-engineers/SpaceEngineersDedicated/DedicatedServer64/: No such file or directory
space-engineers-dedicated-docker-linux | wine: cannot find L"/appdata/space-engineers/SpaceEngineersDedicated/DedicatedServer64/SpaceEngineersDedicated.exe"
space-engineers-dedicated-docker-linux | ls: cannot access '/appdata/space-engineers/Plugins/*.dll': No such file or directory
space-engineers-dedicated-docker-linux | mkdir: cannot create directory '/home/wine/.steam/steamcmd': Permission denied
space-engineers-dedicated-docker-linux | cp: cannot create regular file '/home/wine/.steam/steamcmd/': Not a directory
space-engineers-dedicated-docker-linux | cp: cannot create regular file '/home/wine/.steam/steamcmd/linux32/': No such file or directory
space-engineers-dedicated-docker-linux | /usr/games/steamcmd: 24: exec: /home/wine/.steam/steamcmd/steamcmd.sh: not found
space-engineers-dedicated-docker-linux | /entrypoint-space_engineers.bash: line 3: /home/wine/.bash_profile: No such file or directory
space-engineers-dedicated-docker-linux | /entrypoint-space_engineers.bash: line 4: cd: /appdata/space-engineers/SpaceEngineersDedicated/DedicatedServer64/: No such file or directory
space-engineers-dedicated-docker-linux | wine: cannot find L"/appdata/space-engineers/SpaceEngineersDedicated/DedicatedServer64/SpaceEngineersDedicated.exe"
space-engineers-dedicated-docker-linux | ls: cannot access '/appdata/space-engineers/Plugins/*.dll': No such file or directory
space-engineers-dedicated-docker-linux | mkdir: cannot create directory '/home/wine/.steam/steamcmd': Permission denied
space-engineers-dedicated-docker-linux | cp: cannot create regular file '/home/wine/.steam/steamcmd/': Not a directory
space-engineers-dedicated-docker-linux | cp: cannot create regular file '/home/wine/.steam/steamcmd/linux32/': No such file or directory
space-engineers-dedicated-docker-linux | /usr/games/steamcmd: 24: exec: /home/wine/.steam/steamcmd/steamcmd.sh: not found
space-engineers-dedicated-docker-linux | /entrypoint-space_engineers.bash: line 3: /home/wine/.bash_profile: No such file or directory
space-engineers-dedicated-docker-linux | /entrypoint-space_engineers.bash: line 4: cd: /appdata/space-engineers/SpaceEngineersDedicated/DedicatedServer64/: No such file or directory
space-engineers-dedicated-docker-linux | wine: cannot find L"/appdata/space-engineers/SpaceEngineersDedicated/DedicatedServer64/SpaceEngineersDedicated.exe"
space-engineers-dedicated-docker-linux | ls: cannot access '/appdata/space-engineers/Plugins/*.dll': No such file or directory
space-engineers-dedicated-docker-linux | mkdir: cannot create directory '/home/wine/.steam/steamcmd': Permission denied
space-engineers-dedicated-docker-linux | cp: cannot create regular file '/home/wine/.steam/steamcmd/': Not a directory
space-engineers-dedicated-docker-linux | cp: cannot create regular file '/home/wine/.steam/steamcmd/linux32/': No such file or directory
space-engineers-dedicated-docker-linux | /usr/games/steamcmd: 24: exec: /home/wine/.steam/steamcmd/steamcmd.sh: not found
space-engineers-dedicated-docker-linux | /entrypoint-space_engineers.bash: line 3: /home/wine/.bash_profile: No such file or directory
space-engineers-dedicated-docker-linux | /entrypoint-space_engineers.bash: line 4: cd: /appdata/space-engineers/SpaceEngineersDedicated/DedicatedServer64/: No such file or directory
space-engineers-dedicated-docker-linux | wine: cannot find L"/appdata/space-engineers/SpaceEngineersDedicated/DedicatedServer64/SpaceEngineersDedicated.exe"
space-engineers-dedicated-docker-linux | ls: cannot access '/appdata/space-engineers/Plugins/*.dll': No such file or directory
space-engineers-dedicated-docker-linux | mkdir: cannot create directory '/home/wine/.steam/steamcmd': Permission denied
space-engineers-dedicated-docker-linux | cp: cannot create regular file '/home/wine/.steam/steamcmd/': Not a directory
space-engineers-dedicated-docker-linux | cp: cannot create regular file '/home/wine/.steam/steamcmd/linux32/': No such file or directory
space-engineers-dedicated-docker-linux | /usr/games/steamcmd: 24: exec: /home/wine/.steam/steamcmd/steamcmd.sh: not found
space-engineers-dedicated-docker-linux | /entrypoint-space_engineers.bash: line 3: /home/wine/.bash_profile: No such file or directory
space-engineers-dedicated-docker-linux | /entrypoint-space_engineers.bash: line 4: cd: /appdata/space-engineers/SpaceEngineersDedicated/DedicatedServer64/: No such file or directory
space-engineers-dedicated-docker-linux | wine: cannot find L"/appdata/space-engineers/SpaceEngineersDedicated/DedicatedServer64/SpaceEngineersDedicated.exe"
space-engineers-dedicated-docker-linux | ls: cannot access '/appdata/space-engineers/Plugins/*.dll': No such file or directory
space-engineers-dedicated-docker-linux | mkdir: cannot create directory '/home/wine/.steam/steamcmd': Permission denied
space-engineers-dedicated-docker-linux | cp: cannot create regular file '/home/wine/.steam/steamcmd/': Not a directory
space-engineers-dedicated-docker-linux | cp: cannot create regular file '/home/wine/.steam/steamcmd/linux32/': No such file or directory
space-engineers-dedicated-docker-linux | /usr/games/steamcmd: 24: exec: /home/wine/.steam/steamcmd/steamcmd.sh: not found
space-engineers-dedicated-docker-linux | /entrypoint-space_engineers.bash: line 3: /home/wine/.bash_profile: No such file or directory
space-engineers-dedicated-docker-linux | /entrypoint-space_engineers.bash: line 4: cd: /appdata/space-engineers/SpaceEngineersDedicated/DedicatedServer64/: No such file or directory
space-engineers-dedicated-docker-linux | wine: cannot find L"/appdata/space-engineers/SpaceEngineersDedicated/DedicatedServer64/SpaceEngineersDedicated.exe"
space-engineers-dedicated-docker-linux | ls: cannot access '/appdata/space-engineers/Plugins/*.dll': No such file or directory
space-engineers-dedicated-docker-linux | mkdir: cannot create directory '/home/wine/.steam/steamcmd': Permission denied
space-engineers-dedicated-docker-linux | cp: cannot create regular file '/home/wine/.steam/steamcmd/': Not a directory
space-engineers-dedicated-docker-linux | cp: cannot create regular file '/home/wine/.steam/steamcmd/linux32/': No such file or directory
space-engineers-dedicated-docker-linux | /usr/games/steamcmd: 24: exec: /home/wine/.steam/steamcmd/steamcmd.sh: not found
space-engineers-dedicated-docker-linux | /entrypoint-space_engineers.bash: line 3: /home/wine/.bash_profile: No such file or directory
space-engineers-dedicated-docker-linux | /entrypoint-space_engineers.bash: line 4: cd: /appdata/space-engineers/SpaceEngineersDedicated/DedicatedServer64/: No such file or directory
space-engineers-dedicated-docker-linux | wine: cannot find L"/appdata/space-engineers/SpaceEngineersDedicated/DedicatedServer64/SpaceEngineersDedicated.exe"
space-engineers-dedicated-docker-linux | ls: cannot access '/appdata/space-engineers/Plugins/*.dll': No such file or directory
space-engineers-dedicated-docker-linux | mkdir: cannot create directory '/home/wine/.steam/steamcmd': Permission denied
space-engineers-dedicated-docker-linux | cp: cannot create regular file '/home/wine/.steam/steamcmd/': Not a directory
space-engineers-dedicated-docker-linux | cp: cannot create regular file '/home/wine/.steam/steamcmd/linux32/': No such file or directory
space-engineers-dedicated-docker-linux | /usr/games/steamcmd: 24: exec: /home/wine/.steam/steamcmd/steamcmd.sh: not found
space-engineers-dedicated-docker-linux | /entrypoint-space_engineers.bash: line 3: /home/wine/.bash_profile: No such file or directory
space-engineers-dedicated-docker-linux | /entrypoint-space_engineers.bash: line 4: cd: /appdata/space-engineers/SpaceEngineersDedicated/DedicatedServer64/: No such file or directory
space-engineers-dedicated-docker-linux | wine: cannot find L"/appdata/space-engineers/SpaceEngineersDedicated/DedicatedServer64/SpaceEngineersDedicated.exe"
space-engineers-dedicated-docker-linux | ls: cannot access '/appdata/space-engineers/Plugins/*.dll': No such file or directory
space-engineers-dedicated-docker-linux | mkdir: cannot create directory '/home/wine/.steam/steamcmd': Permission denied
space-engineers-dedicated-docker-linux | cp: cannot create regular file '/home/wine/.steam/steamcmd/': Not a directory
space-engineers-dedicated-docker-linux | cp: cannot create regular file '/home/wine/.steam/steamcmd/linux32/': No such file or directory
space-engineers-dedicated-docker-linux | /usr/games/steamcmd: 24: exec: /home/wine/.steam/steamcmd/steamcmd.sh: not found
space-engineers-dedicated-docker-linux | /entrypoint-space_engineers.bash: line 3: /home/wine/.bash_profile: No such file or directory
space-engineers-dedicated-docker-linux | /entrypoint-space_engineers.bash: line 4: cd: /appdata/space-engineers/SpaceEngineersDedicated/DedicatedServer64/: No such file or directory
space-engineers-dedicated-docker-linux | wine: cannot find L"/appdata/space-engineers/SpaceEngineersDedicated/DedicatedServer64/SpaceEngineersDedicated.exe"
space-engineers-dedicated-docker-linux | ls: cannot access '/appdata/space-engineers/Plugins/*.dll': No such file or directory
space-engineers-dedicated-docker-linux | mkdir: cannot create directory '/home/wine/.steam/steamcmd': Permission denied
space-engineers-dedicated-docker-linux | cp: cannot create regular file '/home/wine/.steam/steamcmd/': Not a directory
space-engineers-dedicated-docker-linux | cp: cannot create regular file '/home/wine/.steam/steamcmd/linux32/': No such file or directory
space-engineers-dedicated-docker-linux | /usr/games/steamcmd: 24: exec: /home/wine/.steam/steamcmd/steamcmd.sh: not found
space-engineers-dedicated-docker-linux | /entrypoint-space_engineers.bash: line 3: /home/wine/.bash_profile: No such file or directory
space-engineers-dedicated-docker-linux | /entrypoint-space_engineers.bash: line 4: cd: /appdata/space-engineers/SpaceEngineersDedicated/DedicatedServer64/: No such file or directory
space-engineers-dedicated-docker-linux | wine: cannot find L"/appdata/space-engineers/SpaceEngineersDedicated/DedicatedServer64/SpaceEngineersDedicated.exe"
space-engineers-dedicated-docker-linux | ls: cannot access '/appdata/space-engineers/Plugins/*.dll': No such file or directory
space-engineers-dedicated-docker-linux | mkdir: cannot create directory '/home/wine/.steam/steamcmd': Permission denied
space-engineers-dedicated-docker-linux | cp: cannot create regular file '/home/wine/.steam/steamcmd/': Not a directory
space-engineers-dedicated-docker-linux | cp: cannot create regular file '/home/wine/.steam/steamcmd/linux32/': No such file or directory
space-engineers-dedicated-docker-linux | /usr/games/steamcmd: 24: exec: /home/wine/.steam/steamcmd/steamcmd.sh: not found
space-engineers-dedicated-docker-linux | /entrypoint-space_engineers.bash: line 3: /home/wine/.bash_profile: No such file or directory
space-engineers-dedicated-docker-linux | /entrypoint-space_engineers.bash: line 4: cd: /appdata/space-engineers/SpaceEngineersDedicated/DedicatedServer64/: No such file or directory
space-engineers-dedicated-docker-linux | wine: cannot find L"/appdata/space-engineers/SpaceEngineersDedicated/DedicatedServer64/SpaceEngineersDedicated.exe"
space-engineers-dedicated-docker-linux exited with code 53

**Comment by woeisme** [comment] 2021-02-09 23:27
looks like permissions problem?

**Comment by mmmaxwwwell** [comment] 2021-02-09 23:34
yeah, you running ./start as root?

**Comment by mmmaxwwwell** [comment] 2021-02-09 23:42
First off, please, for your own sake, don't use the root account. Always make a user with a password that can use sudo.

If I were you, I would delete the space-engineers-dedicated-docker-linux folder, create a regular user, and clone the repo as that user.

You could also chown the ./appdata folder, but just deleting everything and starting over fresh may be the most straightforward.

**Comment by woeisme** [comment] 2021-02-10 12:55
No I'm not running ./start as root. 
I created a separate username and homedir for running this.

**Comment by mmmaxwwwell** [comment] 2021-02-11 03:14
![image](https://user-images.githubusercontent.com/1858305/107599018-4987f480-6bed-11eb-9d7b-8695030dde1f.png)


can you run these commands in the root of the repo and tell me the output
umask
ls -ld ./appdata
ls -ld ./appdata/space-engineers
ls -ld ./appdata/space-engineers/{bins,config}
ls -ld ./appdata/space-engineers/bins/SpaceEngineersDedicated
ls -ld ./appdata/space-engineers/bins/steamcmd
ls -ld ./appdata/space-engineers/config/World
ls -ld ./appdata/space-engineers/config/Plugins

**Comment by woeisme** [comment] 2021-02-11 05:29
uid=1001(SpaceEng) gid=1001(SpaceEng) groups=1001(SpaceEng),27(sudo),126(docker)

0002

drwxrwxr-x 3 SpaceEng SpaceEng 4096 Feb  9 23:09 ./appdata

drwxrwxr-x 4 SpaceEng SpaceEng 4096 Feb  9 23:09 ./appdata/space-engineers

drwxrwxr-x 4 SpaceEng SpaceEng 4096 Feb  9 23:09 ./appdata/space-engineers/bins
drwxrwxr-x 4 SpaceEng SpaceEng 4096 Feb  9 23:09 ./appdata/space-engineers/config

drwxrwxr-x 2 SpaceEng SpaceEng 4096 Feb  9 23:09 ./appdata/space-engineers/bins/SpaceEngineersDedicated

drwxrwxr-x 2 SpaceEng SpaceEng 4096 Feb  9 23:09 ./appdata/space-engineers/bins/steamcmd

drwxrwxr-x 2 SpaceEng SpaceEng 4096 Feb  9 23:09 ./appdata/space-engineers/config/World

drwxrwxr-x 2 SpaceEng SpaceEng 4096 Feb  9 23:09 ./appdata/space-engineers/config/Plugins

**Comment by mmmaxwwwell** [comment] 2021-02-11 22:39
I've reproduced the issue and am working on a solution

**Comment by mmmaxwwwell** [comment] 2021-02-11 23:40
You should be able to work around it by running this in the repo's root ```./stop && sudo chmod -R 777 ./appdata/space-engineers/{bins,config} && ./start```

**Comment by mmmaxwwwell** [comment] 2021-02-11 23:41
I need to come up with a graceful way to handle this that won't break the existing containers, so it may be a bit before I have a fix ready to roll out.

**Comment by woeisme** [comment] 2021-02-12 01:03
> 
> 
> I've reproduced the issue and am working on a solution

okay and thanks for re-opening the issue ticket.

**Comment by woeisme** [comment] 2021-02-12 03:01
> 
> 
> You should be able to work around it by running this in the repo's root `./stop && sudo chmod -R 777 ./appdata/space-engineers/{bins,config} && ./start`

Ran your changes and re-ran ./start

Spout out much of the same errors (copied small sample below). Then seemed to launch, was able to connect and run it!
Is there a way to lock down the multi or do I just use the normal remote admin (https://www.spaceengineersgame.com/dedicated-servers/) tools for doing that?

>space-engineers-dedicated-docker-linux | ls: cannot access '/appdata/space-engineers/Plugins/*.dll': No such file or directory
space-engineers-dedicated-docker-linux | mkdir: cannot create directory '/home/wine/.steam/steamcmd': Permission denied
space-engineers-dedicated-docker-linux | cp: cannot create regular file '/home/wine/.steam/steamcmd/': Not a directory
space-engineers-dedicated-docker-linux | cp: cannot create regular file '/home/wine/.steam/steamcmd/linux32/': No such file or directory
space-engineers-dedicated-docker-linux | /usr/games/steamcmd: 24: exec: /home/wine/.steam/steamcmd/steamcmd.sh: not found
space-engineers-dedicated-docker-linux | /entrypoint-space_engineers.bash: line 3: /home/wine/.bash_profile: No such file or directory
space-engineers-dedicated-docker-linux | /entrypoint-space_engineers.bash: line 4: cd: /appdata/space-engineers/SpaceEngineersDedicated/DedicatedServer64/: No such file or directory
space-engineers-dedicated-docker-linux | wine: cannot find L"/appdata/space-engineers/SpaceEngineersDedicated/DedicatedServer64/SpaceEngineersDedicated.exe"
space-engineers-dedicated-docker-linux | ls: cannot access '/appdata/space-engineers/Plugins/*.dll': No such file or directory
space-engineers-dedicated-docker-linux | mkdir: cannot create directory '/home/wine/.steam/steamcmd': Permission denied
space-engineers-dedicated-docker-linux | cp: cannot create regular file '/home/wine/.steam/steamcmd/': Not a directory
space-engineers-dedicated-docker-linux | cp: cannot create regular file '/home/wine/.steam/steamcmd/linux32/': No such file or directory
space-engineers-dedicated-docker-linux | /usr/games/steamcmd: 24: exec: /home/wine/.steam/steamcmd/steamcmd.sh: not found
space-engineers-dedicated-docker-linux | /entrypoint-space_engineers.bash: line 3: /home/wine/.bash_profile: No such file or directory
space-engineers-dedicated-docker-linux | /entrypoint-space_engineers.bash: line 4: cd: /appdata/space-engineers/SpaceEngineersDedicated/DedicatedServer64/: No such file or directory
space-engineers-dedicated-docker-linux | wine: cannot find L"/appdata/space-engineers/SpaceEngineersDedicated/DedicatedServer64/SpaceEngineersDedicated.exe

**Comment by mmmaxwwwell** [comment] 2021-02-14 04:58
There is a password you can set in the SpaceEngineers-Dedicated.cfg, but you would have to use the windows DS to get that value. If you want more info, ask in the [keen discord](discord.gg/keenswh)

**Comment by mmmaxwwwell** [comment] 2021-02-22 03:16
Would you do me a favor, and pull down the permissions branch into a new folder, and try to start a new world up? I'd love to know if this permissions branch fixes the issue you had originally.

This command will do it, make sure to stop the other server before, if its running, and run it as the SpaceEng user.
```cd && mkdir test && cd test && git clone https://github.com/mmmaxwwwell/space-engineers-dedicated-docker-linux.git && cd space-engineers-dedicated-docker-linux && git checkout permissions && ./start```

Its going to take quite a while to start up as it will rebuild the container from scratch, and then start a new world.

**Comment by UseAfterFreee** [comment] 2021-03-30 17:04
I had the same issue as @woeisme. I tried to build the docker image from the permissions branch and this did in fact fix the issue!

**Comment by MarkL4YG** [comment] 2021-05-19 20:36
Since the container runs as uid ``1000``, you might also change the file permissions accordingly. 🤔 
I used ACLs for this: ``setfacl -Rdm u:1000:rwx appdata`` and ``setfacl -Rm u:1000:rwx appdata``.
It might also be possible to switch to actual volumes.

**Comment by mmmaxwwwell** [comment] 2021-05-20 13:52
So yeah I agree the main thing wrong here is permissions for sure, and it could be improved. I'm not sure what the best fix is, and its not high on my list right now.

I like having the game files in folder mounts, in the same directory. If you know docker, you can change it really easily, and if you don't, then you can still easily understand where the sandbox files are.

I really like the idea of moving the game binaries to volume storage.

as for the config folder permissions issue, how would you handle it @MarkL4YG ?

When I first looked at it, I thought one way could be to chown -R the mounted directories inside the container every time when it starts up. That's what the permissions branch did iirc. This really increased startup time, and while it worked, I don't think its the greatest solution. Maybe your solution is way quicker and fast enough.

Otherwise, I've been thinking somehow we set environment variables for UID and GID in the docker container, then execute the SE binary as the UID user. Maybe the ./start script can prompt the user for info and save the UID and GID to a env file which is included by a reference in by the docker-compose.yml file.

**Comment by mmmaxwwwell** [comment] 2021-06-29 19:17
I'm closing this as wont fix for now

**Closed by mmmaxwwwell** 2021-06-29 19:17 UTC
