### ISSUE TITLE
Issues with SpaceEngineers-Dedicated.cfg when it's missing

### ISSUE THREAD

**Issue by MarkL4YG** [mmmaxwwwell/space-engineers-dedicated-docker-linux#12] opened 2021-05-19 20:33 UTC
Hi,

thank you for sharing this configuration and image 🙂 !

I just wanted to bring the following to your attention:  
The current [check for existence](https://github.com/mmmaxwwwell/space-engineers-dedicated-docker-linux/blob/main/entrypoint.bash#L16) of the ``SpaceEngineers-Dedicated.cfg`` appears to be a little late.  
In my case, the mount ended up as an empty directory mount. Replacing it still leaves an empty directory in ``bins/SpaceEngineersDedicated`` subsequently causing mount errors.  
For inexperienced users, this might cause some frustration as the stack will not start until that empty directory is removed.  
  
My suggestion would be making the check even before the compose file is used, preventing Docker from attempting to mount a nonexistent file.  
  
Depending on your answer/opinion, I might also suggest my change in a PR.

Best regards

**Comment by mmmaxwwwell** [comment] 2021-06-29 19:14
PR encouraged! Also that's a docker feature, not a bug.

**Comment by BaIthamel** [comment] 2022-02-05 08:18
This is still an issue. Having this marked as closed added quite a lot of time before I found it to solve my problem.

**Comment by mmmaxwwwell** [comment] 2022-02-05 13:19
You are using docker, and the behavior you are describing is a feature of docker. I agree it should be handled differently by docker, and I also got stuck on this when I first started.

I will add a bullet point to the tips section that warns about this.

I will also add an exit code and corrosponding check for this condition.

**Comment by mmmaxwwwell** [comment] 2022-02-05 13:41
It looks like the check is already there, and docker is throwing an error when starting when a folder is in place of that file.

```
max@max-desktop:~/github/space-engineers-dedicated-docker-linux$ sudo docker-compose up
Starting space-engineers-dedicated-docker-linux ... error

ERROR: for space-engineers-dedicated-docker-linux  Cannot start service se-server: OCI runtime create failed: container_linux.go:380: starting container process caused: process_linux.go:545: container init caused: rootfs_linux.go:76: mounting "/home/max/github/space-engineers-dedicated-docker-linux/appdata/space-engineers/config/SpaceEngineers-Dedicated.cfg" to rootfs at "/appdata/space-engineers/SpaceEngineersDedicated/SpaceEngineers-Dedicated.cfg" caused: mount through procfd: not a directory: unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type

ERROR: for se-server  Cannot start service se-server: OCI runtime create failed: container_linux.go:380: starting container process caused: process_linux.go:545: container init caused: rootfs_linux.go:76: mounting "/home/max/github/space-engineers-dedicated-docker-linux/appdata/space-engineers/config/SpaceEngineers-Dedicated.cfg" to rootfs at "/appdata/space-engineers/SpaceEngineersDedicated/SpaceEngineers-Dedicated.cfg" caused: mount through procfd: not a directory: unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type
ERROR: Encountered errors while bringing up the project.
```

I know its frustrating to a newcomer, but I think the readme blurb is about all I can do realistically. I'm open to suggestions.

**Closed** 2022-02-05 13:59 UTC

**Comment by BaIthamel** [comment] 2022-02-10 15:37
If you mention in the readme that there are two locations where the cfg file/directory gets referenced one in config and one in bins that would help.  The one in config is listed, the one in bins is not and that is the one I didn't even think to go looking for. The idea that the same file is located twice in the volumes instead of being referenced to the same location did not even occur to me.

**Comment by mmmaxwwwell** [comment] 2022-02-10 16:27
So the file gets overlaid into the bin folder because that's where the dedicated server reads it in from. I probably should just move that bins folder into a docker volume, because I can't think of a reason for a user to need to access that. You shouldn't need to do anything with the bin folder, it should be entirely managed by steamcmd. You should be placing the dedicated server config in the config folder.
