### ISSUE TITLE
Server crash when trying to exit EarthLike atmosphere

### ISSUE THREAD

**Issue by SeanOMik** [mmmaxwwwell/space-engineers-dedicated-docker-linux#23] opened 2021-09-28 03:34 UTC
Anytime a player tries to leave a planet, whether it's in a ship, or in free cam, the server will crash. In free cam, I went about 35km from the surface and waited about a minute. The server becomes unresponsive and the clients show "Connection Error." If I go back to the server console, the server closed.

I first encountered the issue with mods installed so I removed all the mods and completely reset the world and I still had the crash. I don't see any errors inside of the console. I just get a message along the sides of "Server simulation speed slowed down, exiting."

The world works fine on my Windows machine. I used SCP to copy it from my server to my PC and loaded into it. No errors when trying to use free cam or a ship to leave the planet.

**Comment by SeanOMik** [comment] 2021-09-29 00:41
I got the (log file)[https://github.com/mmmaxwwwell/space-engineers-dedicated-docker-linux/files/7248054/SpaceEngineersDedicated_20210928_163216549.log)

**Comment by mmmaxwwwell** [comment] 2021-10-01 00:59
You are running a windows program in wine, things like this happen.

It looks like the watchdog killed the server. You may be able to troubleshoot it further by disabling the watchdog, triggering the condition, and then using lsof to list all the open files. Not sure what the issue is here, haven't seen this before, but sounds like an issue with your storage device. Try moving it to a different drive?

Closing this

**Closed by mmmaxwwwell** 2021-10-01 00:59 UTC
